### ISSUE TITLE
chsi查询成绩次数过多会出现验证码

### ISSUE THREAD

**Issue by laijingwu** [C2CCC/getCetCandidateNumber#1]
chsi查询成绩次数过多会出现验证码，造成查询失败。

**Comment by ChuChencheng** [comment]
😂昨天做着玩的，貌似改个ip就好了？有空再试试

**Comment by laijingwu** [comment]
之前我做的也是chsi的查询成绩，昨天上线以后大量数据后出现验证码，紧急更换了99sushe的。我是用php做的。现在99sushe查准考证号的算法修改了，没法查准考证号。
